blog-ff/routes/web.php
<?php


use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\EditorsChoice;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\StringToSlug;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


Route::get('/', [HomeController::class, 'index'])->name('home');

Route::get('/categories', [CategoryController::class, 'index'])->name('categories');
Route::get('/categories/{category:slug}', [CategoryController::class, 'show'])->name('categories.show');

Route::get('/posts', [PostController::class, 'index'])->name('posts.index');
Route::get('/posts/{post:slug}', [PostController::class, 'show'])->name('posts.show');

Route::get('/editors-choice', [EditorsChoice::class, 'index'])->name('editorsChoice');



Route::prefix('admin')->name('admin.')->middleware('auth')->group(function () {
    Route::get('login', [LoginController::class, 'showLoginForm'])->name('login')->withoutMiddleware('auth');
    Route::post('login', [LoginController::class, 'login'])->withoutMiddleware('auth');
    Route::post('logout', [LoginController::class, 'logout'])->name('logout');

    Route::get('/', function (){
        return view("admin.dashboard");
    })->name('dashboard');

    Route::get('/blog', [PostController::class, 'indexAdmin'])->name('blog');
    Route::get('/blog/create', [PostController::class, 'create'])->name('blog.create');
    Route::post('/blog/create', [PostController::class, 'store'])->name('blog.store');
    Route::get('/blog/{post:slug}', [PostController::class, 'edit'])->name('blog.edit');
    Route::put('/blog/{post:slug}', [PostController::class, 'update'])->name('blog.update');
    Route::delete('/blog/{post:slug}', [PostController::class, 'destroy'])->name('blog.destroy');

    Route::get('/categories', [CategoryController::class, 'indexAdmin'])->name('categories');
    Route::get('/categories/create', [CategoryController::class, 'create'])->name('categories.create');
    Route::post('/categories/create', [CategoryController::class, 'store'])->name('categories.store');
    Route::get('/categories/{category:slug}', [CategoryController::class, 'edit'])->name('categories.edit');
    Route::put('/categories/{category:slug}', [CategoryController::class, 'update'])->name('categories.update');
    Route::delete('/categories/{category:slug}', [CategoryController::class, 'destroy'])->name('categories.destroy');

    Route::get('str-to-slug', [StringToSlug::class, 'index'])->name('strToSlug');

});

blog-ff/resources/views/admin/blog-create.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <div class="container-fluid">
        <h1>Add new blog post</h1>
    </div>
@stop

@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12">
                    <div class="card card-primary">
                        <form role="form" method="post" action="{{ route('admin.blog.store') }}" enctype="multipart/form-data" id="quickForm">
                            @csrf
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Title</label>
                                    <input type="text" name="title" value="{{ old("title") }}" class="form-control title" id="exampleInputEmail1" placeholder="Enter title">
                                    @error('title')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Slug</label>
                                    <input type="text" name="slug" value="{{ old("slug") }}" class="form-control" id="exampleInputPassword1" placeholder="Slug">
                                    @error('slug')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="customFile">Blog Photo</label>

                                    <div class="custom-file">
                                        <input type="file" name="photo" value="{{ old("photo") }}" class="custom-file-input" id="customFile">
                                        <label class="custom-file-label" for="customFile">Choose photo</label>
                                    </div>
                                    @error('photo')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>

                                <div class="form-group">
                                    @empty($categories)
                                        <a href="{{ route('admin.categories.create') }}" class="d-block mb-3 text-danger text-bold">No categories yet, create a category first</a>
                                    @endempty
                                    <label>Category</label>
                                    <select class="select2" multiple="multiple" name="categories[]" data-placeholder="Select a Category" style="width: 100%;">
                                        @foreach($categories as $category)
                                            <option value="{{ $category->id }}" {{ (collect(old('categories'))->contains($category->id)) ? 'selected':'' }}>{{ $category->name }}</option>
                                        @endforeach
                                    </select>
                                    @error('categories')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>

                                <div class="form-group">
                                    <textarea class="textarea" placeholder="Place some text here" name="content"
                                              style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;">{{ old("content") }}</textarea>
                                    @error('content')
                                    <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>

                                <div class="form-group">
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" name="editors_choice" class="custom-control-input" value="1" id="exampleCheck1">
                                        <label class="custom-control-label" for="exampleCheck1">Editor's choice</label>
                                    </div>
                                </div>
                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
            <!-- /.row -->
        </div>
    </section>
@stop

@section('js')
    <script>
        $('.title').on('focusout', function(){
            $.get('{{route('admin.strToSlug')}}?slug=' + $(this).val(), function(slug) {
                console.log(slug)
                $('input[name=slug]').val(slug);
            });
        });

        $('.select2').select2()

        tinymce.init({
            selector: '.textarea'
        });

        bsCustomFileInput.init();
    </script>
@endsection


@section('plugins.Select2', true)
@section('plugins.Tinymce', true)
@section('plugins.BsCustomFileInput', true)

blog-ff/resources/views/admin/blog-edit.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <div class="container-fluid">
        <h1>Edit blog post</h1>
    </div>
@stop

@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12">
                    <div class="card card-primary">
                        <form role="form" method="post" action="{{ route('admin.blog.update', $post->slug) }}" enctype="multipart/form-data" id="quickForm">
                            @csrf
                            @method('put')
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Title</label>
                                    <input type="text" name="title" value="{{ old("title") ?? $post->title ?? "" }}" class="form-control title" id="exampleInputEmail1" placeholder="Enter title">
                                    @error('title')
                                    <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Slug</label>
                                    <input type="text" name="slug" value="{{ old("slug") ?? $post->slug ?? "" }}" class="form-control" id="exampleInputPassword1" placeholder="Slug">
                                    @error('slug')
                                    <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                                @if($post->hasPhoto())
                                    <div class="mb-4">
                                        <img src="{{ $post->photo() }}" class="w-100" alt="">
                                    </div>
                                @endif
                                <div class="form-group">
                                    <label for="customFile">Blog Photo</label>

                                    <div class="custom-file">
                                        <input type="file" name="photo" value="{{ old("photo") }}" class="custom-file-input" id="customFile">
                                        <label class="custom-file-label" for="customFile">Choose photo</label>
                                    </div>
                                    @error('photo')
                                    <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>

                                <div class="form-group">
                                    <label>Category</label>
                                    <select class="select2" multiple="multiple" name="categories[]" data-placeholder="Select a Category" style="width: 100%;">
                                        @foreach($categories as $category)
                                            <option value="{{ $category->id }}" {{ (collect(old('categories') ?? $post->categories->pluck('id') ?? null)->contains($category->id)) ? 'selected':'' }}>{{ $category->name }}</option>
                                        @endforeach
                                    </select>
                                    @error('categories')
                                    <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>

                                <div class="form-group">
                                    <textarea class="textarea" placeholder="Place some text here" name="content"
                                              style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;">{{ old("content") ?? $post->content ?? ""  }}</textarea>
                                    @error('content')
                                    <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>

                                <div class="form-group">
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" @if($post->editors_choice) checked @endif name="editors_choice" class="custom-control-input" value="1" id="exampleCheck1">
                                        <label class="custom-control-label" for="exampleCheck1">Editor's choice</label>
                                    </div>
                                </div>
                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Update</button>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
            <!-- /.row -->
        </div>
    </section>
@stop

@section('js')
    <script>
        $('.title').on('focusout', function(){
            $.get('{{route('admin.strToSlug')}}?slug=' + $(this).val(), function(slug) {
                console.log(slug)
                $('input[name=slug]').val(slug);
            });
        });

        $('.select2').select2()

        tinymce.init({
            selector: '.textarea'
        });

        bsCustomFileInput.init();
    </script>
@endsection


@section('plugins.Select2', true)
@section('plugins.Tinymce', true)
@section('plugins.BsCustomFileInput', true)

blog-ff/resources/views/admin/blog.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <div class="container-fluid">
        <h1>All Blogs</h1>
    </div>
@stop

@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <a class="btn btn-primary text-white" href="{{route('admin.blog.create')}}">
                                <i class="fas fa-plus-circle"></i>
                                <span>Create Post</span>
                            </a>
                        </div>

                        <div class="card-body">
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Title</th>
                                    <th>Photo</th>
                                    <th>Categories</th>
                                    <th>Editors choice</th>
                                    <th>Edit</th>
                                    <th>Delete</th>
                                </tr>
                                </thead>
                                <tbody>
                                @forelse($posts as $post)
                                <tr id="js-row-id-{{$post->id}}">
                                    <td>{{ $post->id }}</td>
                                    <td>{{ $post->title }}</td>
                                    <td>{{ $post->photo ? 'Has photo' : 'No photo' }}</td>
                                    <td>{{ $post->categories }}</td>
                                    <td>{{ $post->editors_choice }}</td>
                                    <td class="text-center"><a href="{{route('admin.blog.edit', $post->slug)}}"><i class="fas fa-edit"></i></a></td>
                                    <td class="text-center">
                                        <span class="js-delete-post-trigger"
                                              style="cursor: pointer"
                                              data-url="{{ route('admin.blog.edit', $post->slug) }}"
                                              data-toggle="modal"
                                              data-target="#modal-danger"
                                        >
                                            <i class="fas fa-trash-alt text-danger"></i>
                                        </span>
                                    </td>
                                </tr>
                                @empty
                                    No Posts yet
                                @endforelse

                                </tbody>
                                <tfoot>
                                <tr>
                                    <th>ID</th>
                                    <th>Title</th>
                                    <th>Photo</th>
                                    <th>Categories</th>
                                    <th>Editors choice</th>
                                    <th>Edit</th>
                                    <th>Delete</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>

    <div class="modal fade" id="modal-danger">
        <div class="modal-dialog">
            <div class="modal-content bg-danger">
                <div class="modal-header">
                    <h4 class="modal-title">Are you sure you?</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer justify-content-start">
                    <button type="button" class="btn btn-outline-light" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-outline-light js-delete-post">Delete</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
@stop

@section('js')
    <script>
        const $table = $("#example1").DataTable({
            "responsive": true,
            "autoWidth": false,
        });

        $('.js-delete-post-trigger').on('click', function () {
            const url = $(this).data('url');

            $('.js-delete-post').data('url', url);
        })

        $('.js-delete-post').on('click', function () {
            const url = $(this).data('url');

            $.ajax(url, {
                method: 'delete',
                data: {
                    "_token": "{{csrf_token()}}"
                },
                success: (response) => {
                    const Toast = Swal.mixin({
                        toast: true,
                        position: 'top-end',
                        showConfirmButton: false,
                        timer: 3000,
                        timerProgressBar: true,
                        didOpen: (toast) => {
                            toast.addEventListener('mouseenter', Swal.stopTimer)
                            toast.addEventListener('mouseleave', Swal.resumeTimer)
                        }
                    })

                    Toast.fire({
                        icon: 'success',
                        title: 'Deleted sucessfully'
                    })

                    $table.row(`#js-row-id-${response.id}`)
                        .remove()
                        .draw();
                },
                error: (data) => {
                    const Toast = Swal.mixin({
                        toast: true,
                        position: 'top-end',
                        showConfirmButton: false,
                        timer: 3000,
                        timerProgressBar: true,
                        didOpen: (toast) => {
                            toast.addEventListener('mouseenter', Swal.stopTimer)
                            toast.addEventListener('mouseleave', Swal.resumeTimer)
                        }
                    })

                    Toast.fire({
                        icon: 'error',
                        title: 'Server  Error, contact support'
                    })
                }
            })

            $(this).closest('.modal').modal('hide');
        })
    </script>
@stop

@section('plugins.Datatables', true)
@section('plugins.Sweetalert2', true)

blog-ff/resources/views/admin/category.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <div class="container-fluid">
        <h1>All Categories</h1>
    </div>
@stop

@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <a class="btn btn-primary text-white" href="{{route('admin.categories.create')}}">
                                <i class="fas fa-plus-circle"></i>
                                <span>Create Category</span>
                            </a>
                        </div>

                        <div class="card-body">
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Photo</th>
                                    <th>Description</th>
                                    <th>Edit</th>
                                    <th>Delete</th>
                                </tr>
                                </thead>
                                <tbody>
                                @forelse($categories as $category)
                                    <tr id="js-row-id-{{ $category->id }}">
                                        <td>{{ $category->id }}</td>
                                        <td>{{ $category->name }}</td>
                                        <td>{{ $category->photo ? 'Has photo' : 'No photo' }}</td>
                                        <td>{{ $category->description }}</td>
                                        <td class="text-center"><a href="{{route('admin.categories.edit', $category->slug)}}"><i class="fas fa-edit"></i></a></td>
                                        <td class="text-center">
                                        <span class="js-delete-post-trigger"
                                              style="cursor: pointer"
                                              data-url="{{ route('admin.categories.destroy', $category->slug) }}"
                                              data-toggle="modal"
                                              data-target="#modal-danger"
                                        >
                                            <i class="fas fa-trash-alt text-danger"></i>
                                        </span>
                                        </td>
                                    </tr>
                                @empty
                                    No Categories yet
                                @endforelse

                                </tbody>
                                <tfoot>
                                <tr>
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Photo</th>
                                    <th>Description</th>
                                    <th>Edit</th>
                                    <th>Delete</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>

    <div class="modal fade" id="modal-danger">
        <div class="modal-dialog">
            <div class="modal-content bg-danger">
                <div class="modal-header">
                    <h4 class="modal-title">Are you sure you?</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer justify-content-start">
                    <button type="button" class="btn btn-outline-light" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-outline-light js-delete-post">Delete</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
@stop

@section('js')
    <script>
        const $table = $("#example1").DataTable({
            "responsive": true,
            "autoWidth": false,
        });

        $('.js-delete-post-trigger').on('click', function () {
            const url = $(this).data('url');

            $('.js-delete-post').data('url', url);
        })

        $('.js-delete-post').on('click', function () {
            const url = $(this).data('url');

            $.ajax(url, {
                method: 'delete',
                data: {
                    "_token": "{{csrf_token()}}"
                },
                success: (response) => {
                    const Toast = Swal.mixin({
                        toast: true,
                        position: 'top-end',
                        showConfirmButton: false,
                        timer: 3000,
                        timerProgressBar: true,
                        didOpen: (toast) => {
                            toast.addEventListener('mouseenter', Swal.stopTimer)
                            toast.addEventListener('mouseleave', Swal.resumeTimer)
                        }
                    })

                    Toast.fire({
                        icon: 'success',
                        title: 'Deleted sucessfully'
                    })

                    $table.row(`#js-row-id-${response.id}`)
                        .remove()
                        .draw();
                },
                error: (data) => {
                    const Toast = Swal.mixin({
                        toast: true,
                        position: 'top-end',
                        showConfirmButton: false,
                        timer: 3000,
                        timerProgressBar: true,
                        didOpen: (toast) => {
                            toast.addEventListener('mouseenter', Swal.stopTimer)
                            toast.addEventListener('mouseleave', Swal.resumeTimer)
                        }
                    })

                    Toast.fire({
                        icon: 'error',
                        title: 'Server  Error, contact support'
                    })
                }
            })

            $(this).closest('.modal').modal('hide');
        })
    </script>
@stop

@section('plugins.Datatables', true)
@section('plugins.Sweetalert2', true)

blog-ff/resources/views/admin/dashboard.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>PuppyCo</h1>
@stop

@section('content')
    <p>Make puppies great again!</p>
@stop